# 개발 환경을 위한 설정 파일(h2 데이터베이스 사용)
# H2 Database Configuration for Testing
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate DDL Auto 설정 (create, update, validate, none)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
